name: Tests

on:
  workflow_call:

permissions: {}

jobs:
  build:
    name: Unified Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      
    steps:
      - name: Tests
        uses: ./.github/actions/tests/
